In [74]:
# Lab 1 (Part A)
# [1]
# At first, please find the required dataset for this lab named as 'housing.data1.txt'. 
# You need to upload the dataset to your Google Colab environment first. Then import 
# the required packages like below.
import pandas as pd
import numpy as np

# [2] Import your dataset using pandas and Create a dataframe
dataset = pd.read_csv('housing.data1.csv', header = None, sep = '\s+')

In [56]:
# [3] Convert your dataset to csv file
# [4] Then use the print() function to generate output
print(dataset)
X = dataset.iloc[:,:].values

          0     1       2      3       4       5         6        7      8   \
0    0.00632  18.0   2.310  0.000  0.5380   6.575   65.2000   4.0900    1.0   
1    0.00000   0.0   0.469  6.421  4.9671   2.000  242.0000  17.8000  396.9   
2    0.02729   0.0   7.070  0.000  0.4690   7.185   61.1000   4.9671    2.0   
3    0.03237   0.0   2.180  0.000  0.4580   6.998   45.8000   6.0622    3.0   
4    0.06905   0.0   0.000  0.458  7.1470  54.200    6.0622   3.0000  222.0   
..       ...   ...     ...    ...     ...     ...       ...      ...    ...   
501  0.06263   0.0  11.930  0.000  0.5730   6.593   69.1000   2.4786    1.0   
502  0.04527   0.0  20.600    NaN     NaN     NaN       NaN      NaN    NaN   
503  0.06076   0.0  11.930  0.000  0.5730   6.976   91.0000   2.1675    1.0   
504  0.10959   0.0  11.930  0.000  0.5730   6.794   89.3000   2.3889    1.0   
505  0.04741   0.0  11.930  0.000  0.5730   6.030   80.8000   2.5050    1.0   

         9      10      11     12    13  
0    296.

In [57]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [0.0000e+00 0.0000e+00 4.6900e-01 ...        nan        nan        nan]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


In [58]:
# [5] Learn about head() function and the purpose of it. Use the head() function
dataset.head()

0     1      2      3       4       5         6        7      8   \
0  0.00632  18.0  2.310  0.000  0.5380   6.575   65.2000   4.0900    1.0   
1  0.00000   0.0  0.469  6.421  4.9671   2.000  242.0000  17.8000  396.9   
2  0.02729   0.0  7.070  0.000  0.4690   7.185   61.1000   4.9671    2.0   
3  0.03237   0.0  2.180  0.000  0.4580   6.998   45.8000   6.0622    3.0   
4  0.06905   0.0  0.000  0.458  7.1470  54.200    6.0622   3.0000  222.0   

       9      10      11     12    13  
0  296.00   15.3  396.90   4.98  24.0  
1    9.14   21.6     NaN    NaN   NaN  
2  242.00   17.8  392.83   4.03  34.7  
3  222.00   18.7  394.63   2.94  33.4  
4   18.70  396.9    5.33  36.20   NaN

In [59]:
# how you can find about if there is NaN in your dataset. I used a variable named check_nan 
# to store myresult. If you print the variable, then you should get a True as result. 
# That means you have NaN in yourdataset.
check_nan = dataset.isnull().values.any()
print(check_nan)

True


In [69]:
# [7]Next, replace the NaN values with mean value (by using SimpleImputer class)
# Dealing with missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# we want all rows, but only columns 1 & 2
imputer.fit(X[:, :]) 
# transforming, replacing all nan with mean
X[:,:] = imputer.transform(X[:,:]) 

In [70]:
# [8]Check if you still have NaN values in your dataset or not. Recall that your 
# dataset is a numpy array now as you used the SimpleImputer class.
array_has_nan = dataset.isnull().values.any()
print(array_has_nan)

False


In [73]:
# [9]Print your output and see if it’s a numpy array. 
np.array(dataset)

array([[6.32000000e-03, 1.80000000e+01, 2.31000000e+00, ...,
        3.96900000e+02, 4.98000000e+00, 2.40000000e+01],
       [0.00000000e+00, 0.00000000e+00, 4.69000000e-01, ...,
        3.49281783e+02, 1.29052049e+01, 2.25598739e+01],
       [2.72900000e-02, 0.00000000e+00, 7.07000000e+00, ...,
        3.92830000e+02, 4.03000000e+00, 3.47000000e+01],
       ...,
       [6.07600000e-02, 0.00000000e+00, 1.19300000e+01, ...,
        3.96900000e+02, 5.64000000e+00, 2.39000000e+01],
       [1.09590000e-01, 0.00000000e+00, 1.19300000e+01, ...,
        3.93450000e+02, 6.48000000e+00, 2.20000000e+01],
       [4.74100000e-02, 0.00000000e+00, 1.19300000e+01, ...,
        3.96900000e+02, 7.88000000e+00, 1.19000000e+01]])

In [ ]:
# [10]Once you are done, please save your .ipynb file as abc123_1_A.ipynb.